#Replace

#String Manipulations

function replace_example {

Write-Host This function is running the following command
Write-Host ´Filipe Queiroz" -Replace "Queiroz", "Nunes´#Replaces the "Queiroz" part with "Nunes"
"Filipe Queiroz" -Replace "Queiroz", "Nunes" 
}

function select_string_example {

Write-Host This function is running the following command
Write-Host Tipconfig | Select-String "IPv4" #Search for only the strings with "IPv4"
ipconfig | Select-String "IPv4"
}

function select_string_plus_replace {
Write-Host This function is running the following command
Write-Host "ipconfig | Select-String "IPv4" | ForEach-Object {$_ -Replace '.*\s',''} " 
Write-Host ""
ipconfig | Select-String "IPv4" | ForEach-Object {$_ -Replace '.*\s',''} #It iterates over each matching line and removes character based on this REGEX expressio
# For the regex, the expression '.*\s' means ANY CHARACTER (.) fowolled by an WHITE SPACE (\n)it removes any charecter
So than we can return only the IPV4 address
}

function read_from_external_file {
#Random history generated by chat GPT
echo "In 1737, a young scientist named Elias ventured into the thick forests of Prussia to document the elusive Melanocetus, a mythical bird said to glow in the moonlight. For 15 seconds, he stood frozen in awe as the creature, its feathers shimmering like a silver river, flew past him in a graceful arc. Though the bird vanished just as quickly as it had appeared, those fleeting moments would inspire Elias to dedicate his life to studying rare and mysterious creatures, leading to many of the breakthroughs in zoology we know today." > history.txt #creating a file with this text
cat history.txt #reading the txt file
}


function select_string_external_file {
#Random history generated by chat GPT
echo "In 1737, a young scientist named Elias ventured into the thick forests of Prussia to document the elusive Melanocetus, a mythical bird said to glow in the moonlight. For 15 seconds, he stood frozen in awe as the creature, its feathers shimmering like a silver river, flew past him in a graceful arc. Though the bird vanished just as quickly as it had appeared, those fleeting moments would inspire Elias to dedicate his life to studying rare and mysterious creatures, leading to many of the breakthroughs in zoology we know today." > history.txt #creating a file with this text
$matches = cat history.txt | Select-String -Pattern "young" -AllMatches #reading the txt file
$matches.Matches.Count #Counting how many time the word "youn" just appeared in the sected string
}

select_string_external_file

